MyTODO-list/Models/ListItem.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MyTODO_list.Models
{
    public class ListItem
    {
        [Required(ErrorMessage ="You must specify when the event will occur")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM'/'dd'/'yyyy}", ApplyFormatInEditMode = true)]
        public DateTime When { get; set; }

        [Required(ErrorMessage = "You must enter a description")]
        [MaxLength(150, ErrorMessage =
        "The description must be less than 150 characters.")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        [Required(ErrorMessage ="You must specify how long the event will last")]
        [Range(1, 180, ErrorMessage ="Events should last between one minute and 3 hours")]
        public int? Duration { get; set; }
    }
}

MyTODO-list/Controllers/HomeController.cs
using MyTODO_list.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyTODO_list.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
    }
}

MyTODO-list/Controllers/ListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using MyTODO_list.Models;
namespace MyTODO_list.Controllers

{
    public class ListController : Controller
    {
        public ActionResult Create()
        {
            TempData["DataList"] = MvcHtmlString.Create("<h3>" + "Create your TODO-list here" + "<a class=\"clear\" href=\"\">Clear all</a>" + "</h3>" + "<br/>");
            var model = new ListItem();
            return Create(model);
        }

        [HttpPost]
        public ActionResult Create(ListItem data)
        {
            if (ModelState.IsValid)
            {
                if(data.Description!=null)
                TempData["DataList"] = MvcHtmlString.Create( $"{TempData["DataList"]} <div class=\"list\"> {data.Description} {data.When.ToString("dd/mm/yyyy")} {data.Duration} min </div>");
            }
            else
            {
                ModelState.AddModelError("",
                "The data you entered was not valid");
            }

            return View();
        }
    }
}

MyTODO-list/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Welcome!</h2>

<h4>This application is designed for creating your own TODO-list.
    To get started, go to the appropriate tab "Create".</h4>

MyTODO-list/Views/List/Create.cshtml
@model MyTODO_list.Models.ListItem

@{
    ViewBag.Title = "Create";

    <div class="text-danger">
        @Html.ValidationSummary(true)
    </div>
}

<h2>Create</h2>

<div class="editor">

    @using (Html.BeginForm())
    {
        <div class="form-group">
            @Html.LabelFor(m => m.Description)<br />
            @Html.EditorFor(m => m.Description)
            <span class="text-danger">@Html.ValidationMessageFor(m => m.Description)</span>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.When)<br />
            @Html.EditorFor(m => m.When)
            <span class="text-danger">@Html.ValidationMessageFor(m => m.When)</span>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Duration)<br />
            @Html.EditorFor(m => m.Duration)
            <span class="text-danger">@Html.ValidationMessageFor(m => m.Duration)</span>
        </div>
        <button class="btn btn-outline-dark" type="submit">Add</button>
        <input class="btn btn-danger" type="reset" value="Reset"/>
    }

</div>
<br />

<div>@TempData["DataList"]</div>

@{ TempData.Keep("DataList"); }

MyTODO-list/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My TODO-list</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Style.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top navbar-dark bg-dark">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("TODO list", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Create", "Create", "List", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year Nazariy Leut</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/Script.js"></script>
</body>
</html>